---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install common packages
      apt:
        name:
          - vim
          - curl
          - git
          - nano
        state: present

- hosts: db
  become: yes
  tasks:
    - name: Install MySQL
      apt:
        name:
          - mysql-server
          - python3-pymysql
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create MySQL database
      mysql_db:
        name: myapp
        state: present

    - name: Create MySQL user
      mysql_user:
        name: mysqluser
        password: p@ssw0rd
        priv: 'myapp.*:ALL'
        host: '%'
        state: present

- hosts: auth
  become: yes
  tasks:
    - name: Install OpenLDAP
      apt:
        name:
          - slapd
          - ldap-utils
        state: present

    - name: Start OpenLDAP service
      service:
        name: slapd
        state: started
        enabled: yes

- hosts: app
  become: yes
  tasks:
    - name: Install Apache and PHP
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy PHP info file
      copy:
        content: "<?php phpinfo(); ?>"
        dest: /var/www/html/info.php
        
        
        
#Additional tasks for Management
    - name: Install rsync
      apt:
        name: rsync
        state: present

    - name: Create backup script directory
      file:
        path: /home/vagrant/backup_scripts
        state: directory

    -name: Create backup script for db-server
     copy:
        dest: home/vagrant/backup_scripts/backup_dp.sh
        content: |
          #!/bin/bash
          rsync -avz --delete  vagrant @102.168.56.10: //PATH
      mode: '0755'

    - name: Create backup script for auth-server
      copy:
        dest: /home/vagrant/backup_scripts/backup_auth.sh
        content: |
          #!/bin/bash
          rsync -avz --delete vagrant@192.168.56.11:/path/to/backup/ /home/vagrant/backups/auth/
      mode: '0755'


  - name: Schedule backup script for db-server
      cron:
        name: "Backup DB Server"
        minute: "0"
        hour: "2"
        job: "/home/vagrant/backup_scripts/backup_db.sh"

    - name: Schedule backup script for auth-server
      cron:
        name: "Backup Auth Server"
        minute: "0"
        hour: "3"
        job: "/home/vagrant/backup_scripts/backup_auth.sh"

        

